[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.25",
    "langchain-openai>=0.3.16",
    "nltk>=3.9.1",
    "openai>=1.77.0",
    "streamlit>=1.45.0",
]
